version: "3.7"

services:
    db:
        build: ./backend/database
        restart: unless-stopped
        ports:
            - ${PGPORT}:53432
        environment:
            POSTGRES_PASSWORD: ${PGPASSWORD}
            POSTGRES_USER: ${PGUSER}
            POSTGRES_DB: ${PGDATABASE}
        volumes:
            - ee5209-data:/var/lib/postgresql/data

    pgadmin:
        image: dpage/pgadmin4
        restart: unless-stopped
        ports:
            - 3003:80
        environment:
            PGADMIN_DEFAULT_EMAIL: db@email.com
            PGADMIN_DEFAULT_PASSWORD: password
        volumes:
            - ./pgadmin:/var/lib/pgadmin
        depends_on:
            - db

volumes:
    ee5209-data:
