version: "3.7"

services:
    backend:
        build: ./backend
        depends_on:
            - db
        restart: always
        environment:
            BACKEND_PORT: ${BACKEND_PORT}
            PGUSER: ${PGUSER}
            PGHOST: ${PGHOST}
            PGPASSWORD: ${PGPASSWORD}
            PGDATABASE: ${PGDATABASE}
            PGPORT: ${PGPORT}
        ports:
            - ${BACKEND_PORT}:${BACKEND_PORT}
        command: yarn dev
        volumes:
            - ./backend:/backend

    db:
        image: postgres:latest
        restart: always
        ports:
            - ${DB_PORT}:53432
        environment:
            POSTGRES_PASSWORD: ${PGPASSWORD}
            POSTGRES_USER: ${PGUSER}
            POSTGRES_DB: ${PGDATABASE}
        volumes:
            - ee5209-mysql-data:/var/lib/postgresql/data

volumes:
    ee5209-mysql-data:
